
    create table tb_coletas (
       id bigint generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        cidade varchar(255),
        complemento varchar(255),
        data_coleta timestamp,
        estado varchar(255),
        quantidade integer,
        rua varchar(255),
        primary key (id)
    );
